#!/usr/bin/env python

import sys

import matplotlib.pyplot as plt
import numpy as np

data = np.loadtxt(sys.stdin)
if data.ndim == 1:
    plt.plot(data)
    plt.title('Single Column')
    plt.xlabel('Index')
    plt.ylabel('Values')
    plt.grid()
    plt.show()
    sys.exit(0)

for i in range(data.shape[1]):
    plt.plot(data[:, i], label=f'${i + 1}')

plt.title('Multiple Columns')
plt.xlabel('Index')
plt.ylabel('Values')
plt.legend()
plt.grid()
plt.show()
