return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "vim",
        "templ",
        "just",
        "cpp",
        "java",
        "make",
        "c",
        "regex",
        "pascal",
        "fsharp",
        "csv",
        "dockerfile",
        "latex",
        "bibtex",
        "c_sharp",
        "go",
        "dart",
        "zig",
        "rust",
        "ebnf",
      },
    },
  },
  {
    "nvim-treesitter/playground",
    cmd = "TSPlaygroundToggle",
  },
}
