#!/bin/bash
alias x='explorer'
alias repo='cd /d/repo'
alias bconf='source ~/.bashrc'
alias vi='nvim'
alias vim='nvim'
alias nvi='nvim'
alias cya='shutdown -s -t 0'
alias bye='shutdown -s -t 0'
alias reboot='shutdown -r -t 0'
alias restart='shutdown -r -t 0'
alias off='shutdown -s -t 0'
alias bios='shutdown -r -t 0 -fw'
alias bootusb='shutdown -r -t 0 -o'
alias rmd='cat *.md | glow '
